# Generated by Django 4.2.17 on 2024-12-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_answer_user_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_char',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_autor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
