# Generated by Django 4.2.17 on 2024-12-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_person_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
