# Generated by Django 4.2.17 on 2025-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='right_answer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=50),
        ),
    ]
