# Generated by Django 4.2.17 on 2025-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_answer_right_answer_alter_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(default=False),
        ),
    ]
