# Generated by Django 4.2.17 on 2025-01-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_answer_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='right_answer',
            field=models.BooleanField(default=True),
        ),
    ]
